from datetime import datetime

correct_category_dicts = [{
    "category_id": "a",
    "color": "#FF0000",
    "max_points": 1500,
    "start_time": datetime(2023, 12, 20, 10, 00, 00).strftime("%Y-%m-%dT%H:%M:%S"),
    "inscription_fee": 10,
    "reward_first": 200,
    "reward_second": 100,
    "reward_semi": 50,
    "max_players": 40, },
    {"category_id": "b",
     "color": "#FFFF00",
     "min_points": 800,
     "start_time": datetime(2023, 12, 20, 10, 00, 00).strftime("%Y-%m-%dT%H:%M:%S"),
     "inscription_fee": 20,
     "reward_first": 200,
     "reward_second": 100,
     "reward_semi": 50,
     "max_players": 40, },
    {"category_id": "c",
     "color": "#FFFFFF",
     "min_points": 800,
     "max_points": 2000,
     "start_time": datetime(2023, 12, 20, 10, 00, 00).strftime("%Y-%m-%dT%H:%M:%S"),
     "women_only": True,
     "inscription_fee": 20,
     "reward_first": 200,
     "reward_second": 100,
     "reward_semi": 50,
     "reward_quarter": None,
     "max_players": 40,
     "overbooking_percentage": 10}]

incorrect_category_dicts = [{
    "category_id": "a",
    "color": "#FF0000",
    "max_points": 1500,
    "inscription_fee": 10,
    "reward_first": 200,
    "reward_second": 100,
    "reward_semi": 50,
    "max_players": 40, },
    {"category_id": "b",
     "color": "#FFFF00",
     "min_points": 800,
     "start_time": datetime(2023, 12, 20, 10, 00, 00).strftime("%Y-%m-%dT%H:%M:%S"),
     "inscription_fee": 20,
     "reward_first": 200,
     "reward_second": 100,
     "reward_semi": 50,
     "max_players": 40, }]
