/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIErrorModel
 */
export interface APIErrorModel {
    /**
     * 
     * @type {string}
     * @memberof APIErrorModel
     */
    errorType: string;
    /**
     * 
     * @type {string}
     * @memberof APIErrorModel
     */
    origin: string;
    /**
     * 
     * @type {string}
     * @memberof APIErrorModel
     */
    errorMessage: string;
    /**
     * 
     * @type {any}
     * @memberof APIErrorModel
     */
    payload: any | null;
}

/**
 * Check if a given object implements the APIErrorModel interface.
 */
export function instanceOfAPIErrorModel(value: object): value is APIErrorModel {
    if (!('errorType' in value) || value['errorType'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    return true;
}

export function APIErrorModelFromJSON(json: any): APIErrorModel {
    return APIErrorModelFromJSONTyped(json, false);
}

export function APIErrorModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIErrorModel {
    if (json == null) {
        return json;
    }
    return {
        
        'errorType': json['errorType'],
        'origin': json['origin'],
        'errorMessage': json['errorMessage'],
        'payload': json['payload'],
    };
}

export function APIErrorModelToJSON(json: any): APIErrorModel {
    return APIErrorModelToJSONTyped(json, false);
}

export function APIErrorModelToJSONTyped(value?: APIErrorModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorType': value['errorType'],
        'origin': value['origin'],
        'errorMessage': value['errorMessage'],
        'payload': value['payload'],
    };
}

