/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryInfo
 */
export interface EntryInfo {
    /**
     * 
     * @type {string}
     * @memberof EntryInfo
     */
    categoryId: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntryInfo
     */
    markedAsPresent: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EntryInfo
     */
    markedAsPaid: boolean;
}

/**
 * Check if a given object implements the EntryInfo interface.
 */
export function instanceOfEntryInfo(value: object): value is EntryInfo {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('markedAsPresent' in value) || value['markedAsPresent'] === undefined) return false;
    if (!('markedAsPaid' in value) || value['markedAsPaid'] === undefined) return false;
    return true;
}

export function EntryInfoFromJSON(json: any): EntryInfo {
    return EntryInfoFromJSONTyped(json, false);
}

export function EntryInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'markedAsPresent': json['markedAsPresent'],
        'markedAsPaid': json['markedAsPaid'],
    };
}

export function EntryInfoToJSON(json: any): EntryInfo {
    return EntryInfoToJSONTyped(json, false);
}

export function EntryInfoToJSONTyped(value?: EntryInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'markedAsPresent': value['markedAsPresent'],
        'markedAsPaid': value['markedAsPaid'],
    };
}

