/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntryWithCategory
 */
export interface EntryWithCategory {
    /**
     * 
     * @type {string}
     * @memberof EntryWithCategory
     */
    categoryId: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithCategory
     */
    licenceNo: string;
    /**
     * 
     * @type {string}
     * @memberof EntryWithCategory
     */
    color: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EntryWithCategory
     */
    registrationTime: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof EntryWithCategory
     */
    markedAsPresent: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof EntryWithCategory
     */
    markedAsPaid: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntryWithCategory
     */
    alternateName: string | null;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    minPoints: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    maxPoints: number;
    /**
     * 
     * @type {Date}
     * @memberof EntryWithCategory
     */
    startTime: Date;
    /**
     * 
     * @type {boolean}
     * @memberof EntryWithCategory
     */
    womenOnly: boolean;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    baseRegistrationFee: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    lateRegistrationFee: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    rewardFirst: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    rewardSecond: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    rewardSemi: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    rewardQuarter: number | null;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    maxPlayers: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    overbookingPercentage: number;
    /**
     * 
     * @type {number}
     * @memberof EntryWithCategory
     */
    rank: number;
}

/**
 * Check if a given object implements the EntryWithCategory interface.
 */
export function instanceOfEntryWithCategory(value: object): value is EntryWithCategory {
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('licenceNo' in value) || value['licenceNo'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('registrationTime' in value) || value['registrationTime'] === undefined) return false;
    if (!('markedAsPresent' in value) || value['markedAsPresent'] === undefined) return false;
    if (!('markedAsPaid' in value) || value['markedAsPaid'] === undefined) return false;
    if (!('alternateName' in value) || value['alternateName'] === undefined) return false;
    if (!('minPoints' in value) || value['minPoints'] === undefined) return false;
    if (!('maxPoints' in value) || value['maxPoints'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('womenOnly' in value) || value['womenOnly'] === undefined) return false;
    if (!('baseRegistrationFee' in value) || value['baseRegistrationFee'] === undefined) return false;
    if (!('lateRegistrationFee' in value) || value['lateRegistrationFee'] === undefined) return false;
    if (!('rewardFirst' in value) || value['rewardFirst'] === undefined) return false;
    if (!('rewardSecond' in value) || value['rewardSecond'] === undefined) return false;
    if (!('rewardSemi' in value) || value['rewardSemi'] === undefined) return false;
    if (!('rewardQuarter' in value) || value['rewardQuarter'] === undefined) return false;
    if (!('maxPlayers' in value) || value['maxPlayers'] === undefined) return false;
    if (!('overbookingPercentage' in value) || value['overbookingPercentage'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    return true;
}

export function EntryWithCategoryFromJSON(json: any): EntryWithCategory {
    return EntryWithCategoryFromJSONTyped(json, false);
}

export function EntryWithCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryWithCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'],
        'licenceNo': json['licenceNo'],
        'color': json['color'],
        'registrationTime': (json['registrationTime'] == null ? null : new Date(json['registrationTime'])),
        'markedAsPresent': json['markedAsPresent'],
        'markedAsPaid': json['markedAsPaid'],
        'alternateName': json['alternateName'],
        'minPoints': json['minPoints'],
        'maxPoints': json['maxPoints'],
        'startTime': (new Date(json['startTime'])),
        'womenOnly': json['womenOnly'],
        'baseRegistrationFee': json['baseRegistrationFee'],
        'lateRegistrationFee': json['lateRegistrationFee'],
        'rewardFirst': json['rewardFirst'],
        'rewardSecond': json['rewardSecond'],
        'rewardSemi': json['rewardSemi'],
        'rewardQuarter': json['rewardQuarter'],
        'maxPlayers': json['maxPlayers'],
        'overbookingPercentage': json['overbookingPercentage'],
        'rank': json['rank'],
    };
}

export function EntryWithCategoryToJSON(json: any): EntryWithCategory {
    return EntryWithCategoryToJSONTyped(json, false);
}

export function EntryWithCategoryToJSONTyped(value?: EntryWithCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryId': value['categoryId'],
        'licenceNo': value['licenceNo'],
        'color': value['color'],
        'registrationTime': (value['registrationTime'] == null ? null : (value['registrationTime'] as any).toISOString()),
        'markedAsPresent': value['markedAsPresent'],
        'markedAsPaid': value['markedAsPaid'],
        'alternateName': value['alternateName'],
        'minPoints': value['minPoints'],
        'maxPoints': value['maxPoints'],
        'startTime': ((value['startTime']).toISOString()),
        'womenOnly': value['womenOnly'],
        'baseRegistrationFee': value['baseRegistrationFee'],
        'lateRegistrationFee': value['lateRegistrationFee'],
        'rewardFirst': value['rewardFirst'],
        'rewardSecond': value['rewardSecond'],
        'rewardSemi': value['rewardSemi'],
        'rewardQuarter': value['rewardQuarter'],
        'maxPlayers': value['maxPlayers'],
        'overbookingPercentage': value['overbookingPercentage'],
        'rank': value['rank'],
    };
}

