/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Player } from './Player';
import {
    PlayerFromJSON,
    PlayerFromJSONTyped,
    PlayerToJSON,
    PlayerToJSONTyped,
} from './Player';

/**
 * 
 * @export
 * @interface GetAllPlayersResponse
 */
export interface GetAllPlayersResponse {
    /**
     * 
     * @type {Array<Player>}
     * @memberof GetAllPlayersResponse
     */
    players: Array<Player>;
}

/**
 * Check if a given object implements the GetAllPlayersResponse interface.
 */
export function instanceOfGetAllPlayersResponse(value: object): value is GetAllPlayersResponse {
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function GetAllPlayersResponseFromJSON(json: any): GetAllPlayersResponse {
    return GetAllPlayersResponseFromJSONTyped(json, false);
}

export function GetAllPlayersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPlayersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(PlayerFromJSON)),
    };
}

export function GetAllPlayersResponseToJSON(json: any): GetAllPlayersResponse {
    return GetAllPlayersResponseToJSONTyped(json, false);
}

export function GetAllPlayersResponseToJSONTyped(value?: GetAllPlayersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': ((value['players'] as Array<any>).map(PlayerToJSON)),
    };
}

