/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntryWithPlayer } from './EntryWithPlayer';
import {
    EntryWithPlayerFromJSON,
    EntryWithPlayerFromJSONTyped,
    EntryWithPlayerToJSON,
    EntryWithPlayerToJSONTyped,
} from './EntryWithPlayer';

/**
 * 
 * @export
 * @interface GetEntriesByCategoryResponse
 */
export interface GetEntriesByCategoryResponse {
    /**
     * 
     * @type {{ [key: string]: Array<EntryWithPlayer>; }}
     * @memberof GetEntriesByCategoryResponse
     */
    entriesByCategory: { [key: string]: Array<EntryWithPlayer>; };
}

/**
 * Check if a given object implements the GetEntriesByCategoryResponse interface.
 */
export function instanceOfGetEntriesByCategoryResponse(value: object): value is GetEntriesByCategoryResponse {
    if (!('entriesByCategory' in value) || value['entriesByCategory'] === undefined) return false;
    return true;
}

export function GetEntriesByCategoryResponseFromJSON(json: any): GetEntriesByCategoryResponse {
    return GetEntriesByCategoryResponseFromJSONTyped(json, false);
}

export function GetEntriesByCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEntriesByCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entriesByCategory': json['entriesByCategory'],
    };
}

export function GetEntriesByCategoryResponseToJSON(json: any): GetEntriesByCategoryResponse {
    return GetEntriesByCategoryResponseToJSONTyped(json, false);
}

export function GetEntriesByCategoryResponseToJSONTyped(value?: GetEntriesByCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entriesByCategory': value['entriesByCategory'],
    };
}

