/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayBody
 */
export interface PayBody {
    /**
     * 
     * @type {number}
     * @memberof PayBody
     */
    amount: number;
}

/**
 * Check if a given object implements the PayBody interface.
 */
export function instanceOfPayBody(value: object): value is PayBody {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PayBodyFromJSON(json: any): PayBody {
    return PayBodyFromJSONTyped(json, false);
}

export function PayBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayBody {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
    };
}

export function PayBodyToJSON(json: any): PayBody {
    return PayBodyToJSONTyped(json, false);
}

export function PayBodyToJSONTyped(value?: PayBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

