/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterEntriesBody
 */
export interface RegisterEntriesBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterEntriesBody
     */
    categoryIds: Array<string>;
}

/**
 * Check if a given object implements the RegisterEntriesBody interface.
 */
export function instanceOfRegisterEntriesBody(value: object): value is RegisterEntriesBody {
    if (!('categoryIds' in value) || value['categoryIds'] === undefined) return false;
    return true;
}

export function RegisterEntriesBodyFromJSON(json: any): RegisterEntriesBody {
    return RegisterEntriesBodyFromJSONTyped(json, false);
}

export function RegisterEntriesBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterEntriesBody {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryIds': json['categoryIds'],
    };
}

export function RegisterEntriesBodyToJSON(json: any): RegisterEntriesBody {
    return RegisterEntriesBodyToJSONTyped(json, false);
}

export function RegisterEntriesBodyToJSONTyped(value?: RegisterEntriesBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categoryIds': value['categoryIds'],
    };
}

