/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterEntriesResponse
 */
export interface RegisterEntriesResponse {
    /**
     * 
     * @type {number}
     * @memberof RegisterEntriesResponse
     */
    amountToPay: number;
}

/**
 * Check if a given object implements the RegisterEntriesResponse interface.
 */
export function instanceOfRegisterEntriesResponse(value: object): value is RegisterEntriesResponse {
    if (!('amountToPay' in value) || value['amountToPay'] === undefined) return false;
    return true;
}

export function RegisterEntriesResponseFromJSON(json: any): RegisterEntriesResponse {
    return RegisterEntriesResponseFromJSONTyped(json, false);
}

export function RegisterEntriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterEntriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amountToPay': json['amountToPay'],
    };
}

export function RegisterEntriesResponseToJSON(json: any): RegisterEntriesResponse {
    return RegisterEntriesResponseToJSONTyped(json, false);
}

export function RegisterEntriesResponseToJSONTyped(value?: RegisterEntriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amountToPay': value['amountToPay'],
    };
}

