/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
    CategoryToJSONTyped,
} from './Category';

/**
 * 
 * @export
 * @interface SetCategoryInput
 */
export interface SetCategoryInput {
    /**
     * 
     * @type {Array<Category>}
     * @memberof SetCategoryInput
     */
    categories: Array<Category>;
}

/**
 * Check if a given object implements the SetCategoryInput interface.
 */
export function instanceOfSetCategoryInput(value: object): value is SetCategoryInput {
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function SetCategoryInputFromJSON(json: any): SetCategoryInput {
    return SetCategoryInputFromJSONTyped(json, false);
}

export function SetCategoryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCategoryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function SetCategoryInputToJSON(json: any): SetCategoryInput {
    return SetCategoryInputToJSONTyped(json, false);
}

export function SetCategoryInputToJSONTyped(value?: SetCategoryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': ((value['categories'] as Array<any>).map(CategoryToJSON)),
    };
}

