/* tslint:disable */
/* eslint-disable */
/**
 * USKB Tournament
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetCategoryResponse
 */
export interface SetCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof SetCategoryResponse
     */
    message: string;
}

/**
 * Check if a given object implements the SetCategoryResponse interface.
 */
export function instanceOfSetCategoryResponse(value: object): value is SetCategoryResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SetCategoryResponseFromJSON(json: any): SetCategoryResponse {
    return SetCategoryResponseFromJSONTyped(json, false);
}

export function SetCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SetCategoryResponseToJSON(json: any): SetCategoryResponse {
    return SetCategoryResponseToJSONTyped(json, false);
}

export function SetCategoryResponseToJSONTyped(value?: SetCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

